<?php

namespace Inc;

use Cleantalk\ApbctWP\State;
use PHPUnit\Framework\TestCase;

class TestCleantalkSettings extends TestCase
{
	protected function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
        require_once(CLEANTALK_PLUGIN_DIR . 'inc/cleantalk-settings.php');
		global $apbct;
		$apbct = new State('cleantalk', array('settings', 'data', 'errors', 'remote_calls', 'stats', 'fw_stats'));
	}

    protected function tearDown(): void
    {
        global $apbct;
        unset($apbct);
        parent::tearDown();
    }

	public function testApbctSettingsSetFieldsBotDetector()
	{
		$fields = apbct_settings__set_fields();

		$this->assertArrayHasKey('data_processing', $fields);

		$data_processing_options = $fields['data_processing']['fields'];

		$this->assertArrayNotHasKey('data__bot_detector_enabled', $data_processing_options);
		$this->assertArrayHasKey('bot_detector_state', $data_processing_options);
		$this->assertArrayHasKey('callback', $data_processing_options['bot_detector_state']);
		$this->assertArrayHasKey('long_description', $data_processing_options['bot_detector_state']);
		$this->assertArrayHasKey('display', $data_processing_options['bot_detector_state']);
		$this->assertArrayNotHasKey('parent', $data_processing_options['exclusions__bot_detector']);
	}
}