<?php

namespace Cleantalk\ApbctWP\Tests\PluginSettingsPage;

use Cleantalk\ApbctWP\PluginSettingsPage\SettingsField;
use Cleantalk\ApbctWP\State;
use PHPUnit\Framework\TestCase;
use ReflectionClass;
use ReflectionMethod;

/**
 * Тестовый подкласс для переопределения приватных методов
 */
class SettingsFieldTestable extends SettingsField
{
	public function anyCacheDetectedInEnvironmentPublic(): bool
	{
		return $this->anyCacheDetectedInEnvironment();
	}

	// Переопределяем приватный метод через public-обёртку
	public function getRadioChildrenChunkPublic($option): string
	{
		$reflection = new ReflectionClass($this);
		$method = $reflection->getMethod('getRadioChildrenChunk');
		$method->setAccessible(true);
		return $method->invoke($this, $option);
	}
}

class SettingsFieldTest extends \ApbctTestCase
{
	public function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		global $apbct;
		$apbct = new State('cleantalk', array('settings', 'data', 'errors', 'remote_calls', 'stats', 'fw_stats'));
	}

	/**
	 * Вызов приватного метода через Reflection
	 */
	private function invokePrivateMethod($object, string $methodName, array $parameters = [])
	{
		$reflection = new ReflectionClass(get_class($object));
		$method = $reflection->getMethod($methodName);
		$method->setAccessible(true);

		return $method->invokeArgs($object, $parameters);
	}

	/**
	 * Тест: метод возвращает пустую строку, когда нет childrens
	 */
	public function testGetRadioChildrenChunkReturnsEmptyWhenNoChildrens(): void
	{
		$params = [
			'type' => 'radio',
			'name' => 'forms__check_internal',
		];

		$settingsField = new SettingsField($params);
		$option = ['label' => 'Test Option', 'val' => '1'];

		$result = $this->invokePrivateMethod($settingsField, 'getRadioChildrenChunk', [$option]);

		$this->assertEmpty($result);
	}

	/**
	 * Тест: метод возвращает onchange с childrens_enable
	 */
	public function testGetRadioChildrenChunkReturnsOnchangeWithChildrenEnable(): void
	{
		$params = [
			'type' => 'radio',
			'name' => 'forms__check_internal',
			'childrens' => ['child1', 'child2'],
		];

		$settingsField = new SettingsField($params);
		$option = [
			'label' => 'Test Option',
			'val' => '1',
			'childrens_enable' => true,
		];

		$result = $this->invokePrivateMethod($settingsField, 'getRadioChildrenChunk', [$option]);

		$this->assertStringContainsString('onchange="apbctSettingsDependencies(', $result);
		$this->assertStringContainsString('apbct_setting---child1,apbct_setting---child2', $result);
		$this->assertStringContainsString(', 1)', $result);
	}

	/**
	 * Тест: метод добавляет onApbctCookieTypeChange для data__set_cookies
	 * Принудительно считаем, что кэш обнаружен (anyCacheDetectedInEnvironment = true)
	 */
	public function testGetRadioChildrenChunkAddsCookieHandlerForDataSetCookies(): void
	{
		$params = [
			'type' => 'radio',
			'name' => 'data__set_cookies',
			'childrens' => ['child1'],
		];

		$settingsField = new SettingsField($params);
		$option = [
			'label' => 'Test Option',
			'val' => '1',
			'childrens_enable' => true,
		];

		// Переопределяем anyCacheDetectedInEnvironment через Reflection
		$reflection = new ReflectionClass($settingsField);
		$cacheMethod = $reflection->getMethod('anyCacheDetectedInEnvironment');
		$cacheMethod->setAccessible(true);

		// Создаём тестовый объект с переопределённым методом
		$testableSettingsField = new class($params) extends SettingsField {
			public function anyCacheDetectedInEnvironment(): bool
			{
				return true;
			}
		};

		$result = $this->invokePrivateMethod($testableSettingsField, 'getRadioChildrenChunk', [$option]);

		$this->assertStringContainsString('onApbctCookieTypeChange(event);', $result);
	}

	/**
	 * Тест: метод не добавляет onApbctCookieTypeChange для других настроек
	 */
	public function testGetRadioChildrenChunkDoesNotAddCookieHandlerForOtherSettings(): void
	{
		$params = [
			'type' => 'radio',
			'name' => 'forms__check_internal',
			'childrens' => ['child1'],
		];

		$settingsField = new SettingsField($params);
		$option = [
			'label' => 'Test Option',
			'val' => '1',
			'childrens_enable' => true,
		];

		$result = $this->invokePrivateMethod($settingsField, 'getRadioChildrenChunk', [$option]);

		$this->assertStringNotContainsString('onApbctCookieTypeChange(event);', $result);
	}

	/**
	 * Тест: метод не добавляет onchange, когда нет childrens_enable
	 */
	public function testGetRadioChildrenChunkReturnsEmptyWhenNoChildrenEnable(): void
	{
		$params = [
			'type' => 'radio',
			'name' => 'forms__check_internal',
			'childrens' => ['child1'],
		];

		$settingsField = new SettingsField($params);
		$option = [
			'label' => 'Test Option',
			'val' => '1',
		];

		$result = $this->invokePrivateMethod($settingsField, 'getRadioChildrenChunk', [$option]);

		$this->assertEmpty($result);
	}
}
