<?php

use Cleantalk\ApbctWP\PluginSettingsPage\SummaryAndSupportRenderer;
use Cleantalk\ApbctWP\State;

class TestSummaryAndSupportRenderer extends \PHPUnit\Framework\TestCase
{
	private  $apbct;
	protected function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->apbct = new State('cleantalk', array('settings', 'data', 'errors', 'remote_calls', 'stats', 'fw_stats'));
	}

	public function testRender()
	{
		$renderer = new SummaryAndSupportRenderer($this->apbct);
		$html = $renderer->render();

		// 1. Check for the main container element
		$this->assertStringContainsString(
			'id="apbct_summary_and_support"',
			$html,
			'Main container div should exist'
		);

		// 2. Verify the container is hidden by default
		$this->assertStringContainsString(
			'style="display: none;"',
			$html,
			'Container should be hidden by default'
		);

		// 3. Verify both sections (Summary and Support) exist
		$this->assertStringContainsString(
			'id="apbct_summary_and_support-left_side"',
			$html,
			'Left side (Summary) should exist'
		);

		$this->assertStringContainsString(
			'id="apbct_summary_and_support-right_side"',
			$html,
			'Right side (Support) should exist'
		);

		// 4. Check section headers
		$this->assertStringContainsString(
			'<h3 class="apbct_summary_and_support-side_header">Summary</h3>',
			$html,
			'Summary header should be present'
		);

		$this->assertStringContainsString(
			'<h3 class="apbct_summary_and_support-side_header">Support</h3>',
			$html,
			'Support header should be present'
		);

		// 5. Verify all subheaders exist
		$this->assertStringContainsString(
			'Statistics',
			$html,
			'Statistics subheader should be present'
		);

		$this->assertStringContainsString(
			'Server requirements check',
			$html,
			'Server requirements subheader should be present'
		);

		$this->assertStringContainsString(
			'Connections',
			$html,
			'Connections subheader should be present'
		);

		// 6. Check support buttons and links
		$this->assertStringContainsString(
			'Open Support Ticket',
			$html,
			'Open Support Ticket button should exist'
		);

		$this->assertStringContainsString(
			'CleanTalk Anti-Spam Help',
			$html,
			'CleanTalk Anti-Spam Help link should exist'
		);

		$this->assertStringContainsString(
			'Create Support User',
			$html,
			'Create Support User button should exist'
		);

		// 7. Verify user creation result display elements
		$this->assertStringContainsString(
			'id="apbct_summary_and_support-user_creation_username"',
			$html,
			'Username display element should exist'
		);

		$this->assertStringContainsString(
			'id="apbct_summary_and_support-user_creation_email"',
			$html,
			'Email display element should exist'
		);

		$this->assertStringContainsString(
			'id="apbct_summary_and_support-user_creation_password"',
			$html,
			'Password display element should exist'
		);

		// 8. Check for preloader image
		$this->assertStringContainsString(
			'apbct_preloader_button',
			$html,
			'Preloader image should exist'
		);

		// 9. Verify statistics list container exists
		$this->assertStringContainsString(
			'apbct_summary-list_of_items',
			$html,
			'Summary list container should exist'
		);

		// 10. Verify statistics list items have the correct icon class
		$this->assertStringContainsString(
			'apbct-icon-right-dir',
			$html,
			'Statistics items should have the right-dir icon class'
		);

		// 11. Check for server requirements status icons
		$this->assertStringContainsString(
			'apbct-icon-ok',
			$html,
			'Server requirements should display success icons'
		);

		// 12. Verify the "no failed connections" message
		$this->assertStringContainsString(
			'There are no failed connections to server.',
			$html,
			'Should display message about no failed connections'
		);

		// 13. Check for help icon tooltip trigger
		$this->assertStringContainsString(
			'apbct-icon-help-circled',
			$html,
			'Help icon should be present for settings descriptions'
		);

		// 14. Verify plugin version is displayed
		$this->assertStringContainsString(
			'Plugin version',
			$html,
			'Plugin version information should be displayed'
		);

		// 15. Check that JavaScript function is attached to create user button
		$this->assertStringContainsString(
			'onclick="apbctCreateSupportUser()"',
			$html,
			'Create User button should have onclick handler'
		);

		// 16. Verify all links have target="_blank" for external URLs
		$this->assertStringContainsString(
			'target="_blank"',
			$html,
			'External links should open in new tab'
		);

		// 17. Check that the wrapper structure includes both sides
		$this->assertStringContainsString(
			'id="apbct_summary_and_support-sides_wrap"',
			$html,
			'Sides wrapper container should exist'
		);

		// 18. Verify the result container has all necessary child elements
		$this->assertStringContainsString(
			'apbct_summary_and_support-user_creation_row',
			$html,
			'User creation result should have row structure'
		);
	}
}