# .github/workflows/eslint.yml

name: ESLint # name of the action (displayed in the github interface)

on: # event list
  push: # on push to each of these branches
    branches:
      - dev
      - fix
      - master
  pull_request:
    branches:
      - dev
      - master

env: # environment variables (available in any part of the action)
  NODE_VERSION: 16

jobs: # list of things to do
  linting:
    name: ESLint # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Code Linting
        run: npm run eslint

      - name: Telegram notify
        if: failure()
        uses: Glomberg/matrix-messenger-action@master
        with:
          server: ${{ secrets.MATRIX_SERVER }}
          to: ${{ secrets.MATRIX_EXTERNSION_ROOM }}
          token: ${{ secrets.MATRIX_USER_TOKEN }}
          message: |
            Hi, <strong>${{ github.actor }}</strong>! Your commit for <strong>${{ github.repository }}</strong> 
            contains 💯 the best solution but it have to be fixed!
            <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Auto-Tests <strong>ESLint</strong></a> build failed ⛔!
