name: Notice about releases via Matrix

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Matrix message on release
        uses: Glomberg/matrix-messenger-action@master
        with:
          server: ${{ secrets.MATRIX_SERVER }}
          to: ${{ secrets.MATRIX_NEWS_ROOM }}
          token: ${{ secrets.MATRIX_USER_TOKEN }}
          message: |
            ${{ github.event.repository.description }} <strong>v${{github.event.release.name}}</strong> released
            ${{github.event.release.html_url}}
            
            ${{ github.event.release.body }}
