name: Test Coverage

on:
  push:
    branches: [ Coverage-test ]

env:
  PHP_VERSION: 7.4

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - uses: actions/checkout@v4

      - name: Run PHPUnit Coverage
        uses: Glomberg/phpunit-coverage-action@master
        with:
          phpunit-command: './vendor/bin/phpunit --configuration tests/phpunit.xml'
          min-coverage: '80'

      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg
