name: Test Coverage

on:
  push:
    branches: [ Coverage-test ]

env:
  PHP_VERSION: 7.4

jobs:
  coverage:
    name: PHPUnit code Covarege
    runs-on: ubuntu-22.04
    env:
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: wordpress_test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Run MySQL server
        run: sudo systemctl start mysql

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x ./tests/wp-test-setup.sh

      - name: Install WP develop
        run: ./tests/wp-test-setup.sh wordpress_test root root localhost latest

      - name: Run PHPUnit Coverage
        uses: Glomberg/phpunit-coverage-action@master
        with:
          phpunit-command: './vendor/bin/phpunit --configuration tests/phpunit.xml'
          min-coverage: '80'

      - name: Commit coverage badge
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add coverage.svg
          git commit -m "Update coverage badge"
          git push
